# Generated by Django 4.2.3 on 2023-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='admin'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(default='admin', max_length=200),
        ),
    ]
